"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { calculateExpenseShares, calculateNetBalances, generateSettlementTransfers, type Contribution, type Family, type SplitMethod } from "@/lib/finance";

const initialFamilies: Family[] = [{ id: "ahmed", name: "Ahmed Family", adults: 2, children: 2, infants: 0 }, { id: "rahman", name: "Rahman Family", adults: 2, children: 1, infants: 0 }, { id: "niyas", name: "Niyas Family", adults: 2, children: 0, infants: 1 }, { id: "sameer", name: "Sameer Family", adults: 1, children: 2, infants: 0 }];
type Expense = { id: string; title: string; amount: number; category: string; payerId: string; fundSource: "direct" | "group_fund"; allocations: { familyId: string; amount: number }[] };
const coordinatorId = "ahmed";
const seedContributions: Contribution[] = [{ senderId: "rahman", receiverId: coordinatorId, amount: 1000000 }, { senderId: "niyas", receiverId: coordinatorId, amount: 800000 }, { senderId: "sameer", receiverId: coordinatorId, amount: 1200000 }];
const seedExpenses: Expense[] = [{ id: "1", title: "Dinner at Hotel Grand", amount: 485000, category: "Food", payerId: "ahmed", fundSource: "group_fund", allocations: calculateExpenseShares(485000, initialFamilies, "perPerson") }, { id: "2", title: "Airport transfers", amount: 180000, category: "Transport", payerId: "rahman", fundSource: "direct", allocations: calculateExpenseShares(180000, initialFamilies, "equal") }];
const money = (n: number) => `₹${(n / 100).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;

export default function TripPage() {
  const [families] = useState(initialFamilies); const [expenses, setExpenses] = useState(seedExpenses); const [contributions, setContributions] = useState(seedContributions); const [tab, setTab] = useState<"overview" | "families" | "fund" | "settlement">("overview"); const [modal, setModal] = useState<"expense" | "fund" | null>(null);
  const total = expenses.reduce((s, e) => s + e.amount, 0); const contributed = contributions.filter(c => c.receiverId === coordinatorId).reduce((s, c) => s + c.amount, 0); const fundSpent = expenses.filter(e => e.fundSource === "group_fund").reduce((s, e) => s + e.amount, 0); const fundBalance = contributed - fundSpent;
  const balances = useMemo(() => calculateNetBalances(families.map(f => f.id), expenses, contributions), [families, expenses, contributions]); const transfers = useMemo(() => generateSettlementTransfers(balances), [balances]);
  function addExpense(form: FormData) { const amount = Math.round(Number(form.get("amount")) * 100); if (!amount) return; const fundSource = form.get("fundSource") as Expense["fundSource"]; const payerId = fundSource === "group_fund" ? coordinatorId : String(form.get("payer")); setExpenses([...expenses, { id: crypto.randomUUID(), title: String(form.get("title") || "Trip expense"), amount, category: String(form.get("category")), payerId, fundSource, allocations: calculateExpenseShares(amount, families, form.get("method") as SplitMethod) }]); setModal(null); }
  function addFund(form: FormData) { const amount = Math.round(Number(form.get("amount")) * 100); if (!amount) return; setContributions([...contributions, { senderId: String(form.get("sender")), receiverId: coordinatorId, amount }]); setModal(null); }
  return <main className="shell"><header className="row"><div><Link href="/" className="muted">← All trips</Link><h1 style={{ margin: "15px 0 4px", fontSize: 32 }}>Kashmir Family Trip</h1><p className="muted" style={{ margin: 0 }}>Srinagar · INR · 4 families · Coordinator: Ahmed Family</p></div><div className="row"><button className="btn secondary" onClick={() => setModal("fund")}>＋ Add fund</button><button className="btn" onClick={() => setModal("expense")}>＋ Expense</button></div></header><nav className="row" style={{ justifyContent: "flex-start", borderBottom: "1px solid var(--line)", margin: "28px 0 22px", paddingBottom: 10 }}>{([["overview", "Overview"], ["families", "Families"], ["fund", "Group fund"], ["settlement", "Settlement"]] as const).map(([key, label]) => <button key={key} onClick={() => setTab(key)} style={{ border: 0, background: "transparent", padding: "9px 12px", color: tab === key ? "var(--green)" : "var(--muted)", fontWeight: 700, borderBottom: tab === key ? "2px solid var(--green)" : "2px solid transparent" }}>{label}</button>)}</nav>
    {tab === "overview" && <><section className="grid grid-3"><div className="card"><p className="muted">Group fund balance</p><div className="amount">{money(fundBalance)}</div><p className="muted" style={{ marginBottom: 0 }}>{money(contributed)} contributed · {money(fundSpent)} spent</p></div><div className="card"><p className="muted">Total trip expenses</p><div className="amount">{money(total)}</div><p className="muted" style={{ marginBottom: 0 }}>{expenses.length} recorded expenses</p></div><div className="card"><p className="muted">Settlement transfers</p><div className="amount">{transfers.length}</div><p className="muted" style={{ marginBottom: 0 }}>Based on paid and owed</p></div></section><section className="card" style={{ marginTop: 16 }}><div className="row"><h2 style={{ margin: 0, fontSize: 20 }}>Recent expenses</h2><span className="muted">{expenses.length} total</span></div>{expenses.map(e => <div className="row" key={e.id} style={{ borderTop: "1px solid var(--line)", padding: "16px 0 0", marginTop: 16 }}><div><strong>{e.title}</strong><div className="muted" style={{ fontSize: 13, marginTop: 5 }}>{e.category} · {e.fundSource === "group_fund" ? "paid from group fund" : `paid by ${families.find(f => f.id === e.payerId)?.name}`}</div></div><span className="amount" style={{ fontSize: 20 }}>{money(e.amount)}</span></div>)}</section></>}
    {tab === "families" && <section className="grid">{families.map(f => <div className="card row" key={f.id}><div><h2 style={{ margin: 0, fontSize: 19 }}>{f.name}</h2><p className="muted" style={{ margin: "7px 0 0" }}>{f.adults} adults · {f.children} children · {f.infants} infants</p></div><div style={{ textAlign: "right" }}><div className="muted" style={{ fontSize: 13 }}>Net balance</div><strong style={{ color: balances[f.id] >= 0 ? "var(--green)" : "#b4534b" }}>{balances[f.id] >= 0 ? "+" : "−"}{money(Math.abs(balances[f.id]))}</strong></div></div>)}</section>}
    {tab === "fund" && <section className="grid"><div className="card"><div className="row"><div><p className="muted">Available group fund</p><div className="amount">{money(fundBalance)}</div></div><button className="btn" onClick={() => setModal("fund")}>＋ Record contribution</button></div><div className="grid" style={{ marginTop: 20 }}>{families.map(f => { const amount = contributions.filter(c => c.senderId === f.id && c.receiverId === coordinatorId).reduce((s, c) => s + c.amount, 0); return <div className="row" key={f.id} style={{ borderTop: "1px solid var(--line)", paddingTop: 13 }}><span>{f.name}{f.id === coordinatorId ? " (coordinator)" : ""}</span><strong>{money(amount)}</strong></div>; })}</div></div><div className="card"><h2 style={{ marginTop: 0, fontSize: 19 }}>Fund activity</h2>{contributions.map((c, i) => <div className="row" key={i} style={{ borderTop: "1px solid var(--line)", padding: "13px 0" }}><span>{families.find(f => f.id === c.senderId)?.name} → coordinator</span><strong style={{ color: "var(--green)" }}>+{money(c.amount)}</strong></div>)}{expenses.filter(e => e.fundSource === "group_fund").map(e => <div className="row" key={e.id} style={{ borderTop: "1px solid var(--line)", padding: "13px 0" }}><span>{e.title}</span><strong style={{ color: "#b4534b" }}>−{money(e.amount)}</strong></div>)}</div></section>}
    {tab === "settlement" && <section className="card"><h2 style={{ marginTop: 0 }}>Final settlement</h2><p className="muted">Contributions are included in each family’s net position. The group fund is not treated as a separate family debt.</p>{transfers.map(t => <div className="row" key={`${t.fromId}-${t.toId}`} style={{ padding: "15px 0", borderTop: "1px solid var(--line)" }}><span><strong>{families.find(f => f.id === t.fromId)?.name}</strong><span className="muted"> pays </span><strong>{families.find(f => f.id === t.toId)?.name}</strong></span><span className="amount" style={{ fontSize: 20 }}>{money(t.amount)}</span></div>)}{!transfers.length && <p>All settled 🎉</p>}</section>}
    {modal === "expense" && <Modal title="Quick expense" close={() => setModal(null)} action={addExpense}><div className="field"><label>Amount</label><input name="amount" type="number" min="0.01" step="0.01" autoFocus required /></div><div className="field"><label>What was it?</label><input name="title" placeholder="Dinner" required /></div><div className="field"><label>Category</label><select name="category"><option>Food</option><option>Accommodation</option><option>Transport</option><option>Tickets</option><option>Shopping</option><option>Other</option></select></div><div className="field"><label>Payment source</label><select name="fundSource"><option value="group_fund">Group fund</option><option value="direct">Paid directly by a family</option></select></div><div className="field"><label>Direct payer (if applicable)</label><select name="payer">{families.map(f => <option value={f.id} key={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Split</label><select name="method"><option value="perPerson">Per person</option><option value="equal">Equal per family</option><option value="weighted">Adult / child weighted</option><option value="selected">Selected families</option></select></div></Modal>}
    {modal === "fund" && <Modal title="Record group-fund contribution" close={() => setModal(null)} action={addFund}><p className="muted" style={{ marginTop: 0 }}>Record money received by Ahmed Family for shared trip spending.</p><div className="field"><label>Contributing family</label><select name="sender">{families.filter(f => f.id !== coordinatorId).map(f => <option value={f.id} key={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Amount received</label><input name="amount" type="number" min="0.01" step="0.01" autoFocus required /></div><button className="btn" style={{ width: "100%" }}>Save contribution</button></Modal>}
  </main>;
}
function Modal({ title, close, action, children }: { title: string; close: () => void; action: (form: FormData) => void; children: React.ReactNode }) { return <div style={{ position: "fixed", inset: 0, background: "#18322d66", display: "grid", placeItems: "end center", padding: 14 }}><form action={action} className="card" style={{ width: "min(560px, 100%)", maxHeight: "92vh", overflow: "auto" }}><div className="row"><h2 style={{ margin: 0 }}>{title}</h2><button type="button" onClick={close} className="btn secondary">Close</button></div><div style={{ marginTop: 20 }}>{children}</div>{title === "Quick expense" && <button className="btn" style={{ width: "100%" }}>Save expense</button>}</form></div>; }
