import { pgTable, uuid, text, integer, timestamp, jsonb } from "drizzle-orm/pg-core";

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), username: text("username").notNull().unique(), email: text("email").notNull().unique(), passwordHash: text("password_hash").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const sessions = pgTable("sessions", { id: text("id").primaryKey(), userId: uuid("user_id").references(() => users.id).notNull(), expiresAt: timestamp("expires_at").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const trips = pgTable("trips", { id: uuid("id").defaultRandom().primaryKey(), ownerId: uuid("owner_id").references(() => users.id).notNull(), name: text("name").notNull(), destination: text("destination"), currency: text("currency").default("INR").notNull(), treasurerFamilyId: uuid("treasurer_family_id"), adultWeight: integer("adult_weight").default(100).notNull(), childWeight: integer("child_weight").default(50).notNull(), infantWeight: integer("infant_weight").default(0).notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const families = pgTable("trip_families", { id: uuid("id").defaultRandom().primaryKey(), tripId: uuid("trip_id").references(() => trips.id).notNull(), name: text("name").notNull(), adults: integer("adults").default(0).notNull(), children: integer("children").default(0).notNull(), infants: integer("infants").default(0).notNull() });
export const familyMembers = pgTable("family_members", { id: uuid("id").defaultRandom().primaryKey(), familyId: uuid("family_id").references(() => families.id).notNull(), name: text("name").notNull(), type: text("type").notNull() });
export const expenses = pgTable("expenses", { id: uuid("id").defaultRandom().primaryKey(), tripId: uuid("trip_id").references(() => trips.id).notNull(), payerId: uuid("payer_id").references(() => families.id).notNull(), title: text("title").notNull(), category: text("category").notNull(), amount: integer("amount").notNull(), splitMethod: text("split_method").notNull(), fundSource: text("fund_source").default("direct").notNull(), notes: text("notes"), spentAt: timestamp("spent_at").defaultNow().notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const expenseAllocations = pgTable("expense_allocations", { id: uuid("id").defaultRandom().primaryKey(), expenseId: uuid("expense_id").references(() => expenses.id).notNull(), familyId: uuid("family_id").references(() => families.id).notNull(), amount: integer("amount").notNull() });
export const contributions = pgTable("contributions", { id: uuid("id").defaultRandom().primaryKey(), tripId: uuid("trip_id").references(() => trips.id).notNull(), senderId: uuid("sender_id").references(() => families.id).notNull(), receiverId: uuid("receiver_id").references(() => families.id).notNull(), amount: integer("amount").notNull(), method: text("method"), notes: text("notes"), paidAt: timestamp("paid_at").defaultNow().notNull() });
export const settlements = pgTable("settlements", { id: uuid("id").defaultRandom().primaryKey(), tripId: uuid("trip_id").references(() => trips.id).notNull(), fromId: uuid("from_id").references(() => families.id).notNull(), toId: uuid("to_id").references(() => families.id).notNull(), amount: integer("amount").notNull(), status: text("status").default("pending").notNull(), paidAt: timestamp("paid_at") });
export const settings = pgTable("trip_settings", { tripId: uuid("trip_id").references(() => trips.id).primaryKey(), categories: jsonb("categories").$type<string[]>().default(["Food", "Accommodation", "Transport", "Tickets", "Shopping", "Other"]).notNull() });
